[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Jeff Meyers <jmeyers@colum.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
ferris-says = "0.1"
